Table Circuits {
  id int [pk]
  name varchar
}

Table Athlete {
  id int [pk]
  name varchar 
  birthday datetime
  country varchar
}

Table Judges {
  id int [pk]
  name varchar 
  country varchar
}

Table Countries {
  name varchar [pk]
}

Table IndividualSkate {
  id int [pk]
  competition int [ref: > Competitions.id] 
  athlete varchar
  type boolean // free or short
  score int
}

Table Competitions {
  id int [pk]
  level int // novice, junior, senior
  location varchar 
  time datetime
}

Table TechnicalElements {
  id int [pk]
  skate_id int [ref: > IndividualSkate.id]
  type varchar
  base_score short
  downgraded boolean // Marked by < or <<
  is_second_half boolean // Marked by x next to base value
  edge_call boolean // Marked by e
  is_rep boolean // Marked by +REP 
  failed_requirements boolean // Marked by V
  edge_warning boolean // Marked by ! 
  GOE short 
}

Table PerformanceElement {
  id int [pk]
  skate_id int
  type varchar
  multiplier short
}

Table TechnicalElementReference {
  name varchar [pk]
  base_score int
  is_jump boolean
}

Table JudgesTechnical {
  judge int [ref: > Judges.id]
  technical_element int [ref: > TechnicalElements.id]
  score int 
  dropped boolean
}

Table JudgesPerformance {
  judge int [ref: > Judges.id]
  perfromance_element int [ref: > PerformanceElement.id]
  score int 
}


Ref: Athlete.country > Countries.name
Ref: Judges.country > Countries.name
Ref: IndividualSkate.athlete > Athlete.id















